// Class automatically generated by Dev-C++ New Class wizard

#ifndef ASTEROID_H
#define ASTEROID_H

#include "point2d.h"

#include <cmath>

#define ASTEROID_SPEED 50.0
#define ASTEROID_MAX_ROTATION M_PI_2
#define ASTEROID_SIZE_MULTIPLIER 10.0
#define ASTEROID_SIZE_VARIATION 20.0
#define ASTEROID_CORNERS 9

/*
 * No description
 */
class Asteroid
{
	public:
		// class constructor
		Asteroid();
		Asteroid(Point2D newPosition, int newSize, Point2D newSpeed);
		// class destructor
		~Asteroid();
		
		void advance(double delta);
		void explode();
		
		void draw();
		
		Point2D getPosition();
		Point2D getSpeed();
		int getSize();
		double getExplosionTime();
		
	private:
        Point2D position;
        Point2D speed;
        
        int size;
        double explosionTime;
        double rotation;
        double rotationSpeed;
        
        double sizeVariation[9];
};

#endif // ASTEROID_H
