// Class automatically generated by Dev-C++ New Class wizard

#ifndef ENGINE_H
#define ENGINE_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define TIME_BETWEEN_FRAMES 1000.0/60.0

#define clamp(x, lo, hi) x < lo ? lo : x > hi ? hi : x

#include "asteroid.h"
#include "projectile.h"
#include "ship.h"

/*
 * No description
 */
class Engine
{
	public:
		// class constructor
		Engine();
		// class destructor
		~Engine();
		
		void update(double delta);
		void draw();
	
	private:
        // Game variables
        Ship* ship;
        Projectile* projectiles[20];
        int noProjectiles;
        Asteroid* asteroids[32];
        int noAsteroids;
        
        // Game stats
        int lives;
        int score;
        
        // Inputs
        bool leftPressed;
        bool rightPressed;
        bool accelerationPressed;
        bool firePressed;
        int projectileCooldown;
        
        // Game state tracker
        bool gameOver;
        bool gameWon;
        
        // Helper functions (keeps update() from being too big)
        void getInput();
        void shipUpdateLogic(double delta);
        void projectilesUpdateLogic(double delta);
        void asteroidsUpdateLogic(double delta);
        void projectileAsteroidCollision();
        void shipAsteroidCollision();
        
        // Drawing helper functions
        void drawLive(int x, int y);
        void solidRectangle(int x1, int y1, int x2, int y2);
};

#endif // ENGINE_H
