// Class automatically generated by Dev-C++ New Class wizard

#include "point2d.h" // class's header file

// class constructor
Point2D::Point2D()
{
	// insert your code here
}

// class destructor
Point2D::~Point2D()
{
	// insert your code here
}
