// Class automatically generated by Dev-C++ New Class wizard

#ifndef POINT2D_H
#define POINT2D_H

#include <cmath>

/*
 * No description
 */
class Point2D
{
	public:
        double x;
        double y;
           
		// class constructor
		Point2D() : x(0), y(0) {}
		Point2D(double _x, double _y) : x(_x), y(_y) {}
		Point2D(Point2D other) : x(other.x), y(other.y) {}
		// class destructor
		~Point2D();
		
		double length() { return hypot(x, y); }
		Point2D operator+(Point2D v) { return Point2D(x + v.x, y + v.y); }
		Point2D operator-(Point2D v) { return Point2D(x - v.x, y - v.y); }
		Point2D operator*(double f) { return Point2D(x * f, y * f); }
		Point2D operatir/(double f) { return Point2D(x / f, y / f); }
};

#endif // POINT2D_H
