// Class automatically generated by Dev-C++ New Class wizard

#ifndef PROJECTILE_H
#define PROJECTILE_H

#include "point2d.h"

#define PROJECTILE_SPEED 400

/*
 * No description
 */
class Projectile
{
	public:
		// class constructor
		Projectile(Point2D startPosition, double rotationAngle);
		// class destructor
		~Projectile();
	
	    void advance(double delta);
	    bool isOut();
	    
	    void draw();
	    
	    Point2D getPosition();
	
	private:
        Point2D position;
        Point2D speed;
};

#endif // PROJECTILE_H
