// Class automatically generated by Dev-C++ New Class wizard

#include "projectile.h" // class's header file

#include "engine.h"

#include <graphics.h>

// class constructor
Projectile::Projectile(Point2D startPosition, double rotationAngle)
{                              
	position = startPosition;
	speed = Point2D(sin(rotationAngle), -cos(rotationAngle)) * PROJECTILE_SPEED;
}

// class destructor
Projectile::~Projectile()
{
	// insert your code here
}

void Projectile::advance(double delta)
{
     position += speed * delta;
}

bool Projectile::isOut()
{
     return (position.x < -10 || position.x > WINDOW_WIDTH + 10
         || position.y < -10 || position.y > WINDOW_HEIGHT + 10);
}

void Projectile::draw()
{
     circle((int)position.x, (int)position.y, 5);
}

Point2D Projectile::getPosition()
{
    return position;
}
