// Class automatically generated by Dev-C++ New Class wizard

#ifndef SHIP_H
#define SHIP_H

#include "point2d.h"

#include <cmath>

#define ROTATION_SPEED M_PI
#define MAX_SPEED 100.0
#define SHIP_ACCEL 250.0

/*
 * No description
 */
class Ship
{
	public:
		// class constructor
		Ship();
		// class destructor
		~Ship();
		
	    void advance(double delta);
	    void applyLeftRotation(double delta);
	    void applyRightRotation(double delta);
	    void applyAcceleration(double delta);
	    void explode();
	    void reset();
	    
	    void draw();
  
        Point2D getPosition();
        double getRotation();
        bool isExploded();
        double getExplosionTime();
        
    private:
        Point2D position;
        Point2D speed;
        
        double rotation;
        bool exploded;
        double explosionTime;
};

#endif // SHIP_H
